sudo: false
language: ruby
bundler_args: "--without development production staging"
rvm:
- 2.2.3
addons:
  postgresql: 9.3
  code_climate:
    repo_token: 21524b0b86a59b7e03bf276b2bea678c477f5639fd1263d772e7c5bac8b19d2a
before_script:
- psql -c 'create database travis_ci_test' -U postgres
- cp config/database.yml.travis config/database.yml
- cp config/secrets.yml.travis config/secrets.yml
- RAILS_ENV=test bundle exec rake db:migrate
script:
- CODECLIMATE_REPO_TOKEN=21524b0b86a59b7e03bf276b2bea678c477f5639fd1263d772e7c5bac8b19d2a
  bundle exec rake
notifications:
  slack: wcmc:lKFUwvPWA1ATAwSQWPm1Y3C5
env:
  global:
  - secure: OOwUUEhKfjVkF1c+rNjPgw6OewdZ1wugAXx7V+hA5Qoi4yE0upCl/36gJuVLAW/JaeLhY3moS4u5K0BPSBhLtUwwxOWc6JI1ETi6dmul757PiA/Y81g+j5FJcztC3DwP+PgZ9OqIBzFT7rWaVG5b6VkZTpG5GOsXJXkBOZ+vgSs=
  - secure: GP6ZDdscpkepWAGpk0sInmzswXIegz5FIjdvmU8SMLwhZaJm8SByapHIm6Q8ri9S3zG1N5XS0SmRIeFxFzPdgaACFzGoC0EH/AZ2srypbYdSatgDkiIlyBpvmMZPjDJunBA0OnUaizz91wdoeLRQWntna7n0SawzMfOl4/9uCi8=
  - secure: L2d1T9VN4AtY/QMpiZ/Si3OZRyRRLYJxk0tH/SdJ212A6NNg5UtXheqhm3w65QIkT5DacY749zawS8dJ8m09uwppH72j/NGeXWexSvr4NC+pVzoy9HC08Ol87ykA5wNKlx2hFi+BR/0qeiRxNE35SKz6iAc49pOX1+sDsKeXemM=
after_success:
- openssl aes-256-cbc -k $DEPLOY_KEY -in config/travis_deploy_id_rsa_enc_travis -d -a -out config/travis_deploy_id_rsa
- chmod 600 config/travis_deploy_id_rsa
- bundle exec cap staging deploy
