sudo: false
language: ruby
bundler_args: --without development production staging
rvm:
- 2.2.3
addons:
  postgresql: 9.3
  code_climate:
    repo_token: 21524b0b86a59b7e03bf276b2bea678c477f5639fd1263d772e7c5bac8b19d2a bundle exec rake
before_script:
- psql -c 'create database travis_ci_test' -U postgres
- cp config/database.yml.travis config/database.yml
- cp config/secrets.yml.travis config/secrets.yml
- RAILS_ENV=test bundle exec rake db:migrate
script:
- CODECLIMATE_REPO_TOKEN=21524b0b86a59b7e03bf276b2bea678c477f5639fd1263d772e7c5bac8b19d2a
  bundle exec rake
notifications:
  slack: wcmc:lKFUwvPWA1ATAwSQWPm1Y3C5

env:
  global:
    secure: T4KD+ggvUmCI/1in6gS0kaAePIguX8x1vgOS+IluOhI1DcLdadNcecK5VzdHQiztl1p/QIV5+8c9suiITejpd/U+aFVQSGlA5C3CVYmNa3IfWCPCqF9rLOKCZtcQQlWpp3RGzQY6JkpujN2QQSAs9bYDIjnu/mKDF32UWnJgdb0=
